# Example configuration. You can copy this to your config, and use --config to
# point to it.

users:
  - username: bravo
    # Note: Password is set here, and as a consequence stored in plain text in this
    # file. This approach favors convenience over security, and is practical since there
    # is no client-side implementation of password management yet. If needed, passowrd
    # management can be implemented on client, and then a salted user-specific hash
    # should be stored.
    password: bravo123
    # Optional. If not present, the workspace name defaults to the username.
    workspace: common

labels:
  - name: (unknown)
    allow_multiple: true
    color: '#000'
  - name: blur
    allow_multiple: true
    color: 'green'
  - name: object_no_1
    allow_multiple: false
    color: 'red'

videos:
  - video_file: "video.mkv"
    label_file: "labels.json"
    # Optional. If present, used in the UI instead of video file's basename.
    video_alias: "Video 1"
    # Optional. If present, only these users will be able to see the video.
    acl: ["bravo"]
  - video_file: "video2.mkv"
    label_file: "labels2.json"
