# Example configuration. You can copy this to your config, and use --config to
# point to it.

users:
  - username: bravo
    password: bravo123

labels:
  - name: (unknown)
    allow_multiple: true
    color: '#000'
  - name: blur
    allow_multiple: true
    color: 'green'
  - name: object_no_1
    allow_multiple: false
    color: 'red'

videos:
  - video_file: "video.mkv"
    label_file: "labels.json"
    # Optional. If present, used in the UI instead of video file's basename.
    video_alias: "Video 1"
    # Optional. If present, only these users will be able to see the video.
    acl: ["bravo"]
  - video_file: "video2.mkv"
    label_file: "labels2.json"
